error: old validation sytax
even though validations still work using the old syntax, you
should use the new one for a rails 3.2 book.

see http://guides.rubyonrails.org/active_record_validations_callbacks.html

instead of
  validates_presence_of :foo

you should write
  validates :foo, :presence => true

that way you can actually chain validations for one attribute.

ATTENTION:
this is true for the whole chapter. the syntax is old and should be
rewritten using the new syntax.

i will read the chapter but restrain from correcting anything that
is connected to the issue at hand.

NOTE:
i know that some of these methods were deprecated in rails 3.0 but
still exist (like 'presence'). since the official guide recommends
to use the new validates, i guess, it is the way to go.
this is especially true for methods like 'validates_uniqueness_of'
which have not been added to 3.2 and are still deprecated.

see http://apidock.com/rails/ActiveModel/Validations/ClassMethods/validates
and http://apidock.com/rails/ActiveModel/Validations/HelperMethods